### ISSUE TITLE
Map page refresh bug

### ISSUE THREAD

**Issue by regier21** [upcs/cs341-project-ss2020-ada#52]
Add the same location twice to the map.
Refresh the map.
Try to add the location again.
A popup will say that no more locations can be added, but a new pin will be added to the map. This pin does not go away when remove data is pressed.

**Comment by pirkl21** [comment]
Hey! There's an explanation for this! Currently, each user can only have up to two locations "saved" or stored by the server at any time. Thus, when you try and add a third location, a notification pops up that says no more points can be added! But, we still wanted people to be able to add locations to the map. So instead of adding it to the tracked user data points, the data point Is just added as a marker that will disappear when you refresh the page. 
We'll make sure to make this clearer by the end of the next sprint. Thanks for your comment!

**Comment by pirkl21** [comment]
Fixed the pin not going away when show/hide data button was pressed. Re-designed the alert for max user saved locations to be more clear.
